// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from 'dotenv';
import { defineConfig } from 'prisma/config';

const nodeEnv = process.env.NODE_ENV || 'development';

// * dotenv never overwrites a var already set, so the first match wins.
loadEnv({ path: `.env.${nodeEnv}.local` });
loadEnv({ path: `.env.${nodeEnv}` });
loadEnv({ path: '.env' });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
