// GOAL: DEFINE DEPENDENCY INJECTION TOKENS.
// USED BY MODULE TO PROVIDE THE SERVICE, AND BY CONSUMERS TO INJECT THE SERVICE.
// DEFINES A UNIQUE STRING TOKEN.
export const STORAGE_SERVICE_TOKEN = 'STORAGE_SERVICE_TOKEN'; // INJECTION TOKENS
