//* NAMES OF THE TWO GLOBAL TIERS REGISTERED IN AppThrottlerModule. @nestjs/throttler v6
//* EVALUATES EVERY CONFIGURED THROTTLER ON EVERY REQUEST AND REQUIRES **ALL** OF THEM TO
//* PASS, SO THE TIERS COMPOSE: A BURST CEILING AND A SUSTAINED CEILING APPLY AT ONCE.
export const THROTTLER_SHORT = 'short';
export const THROTTLER_LONG = 'long';

//* EXEMPT A ROUTE FROM EVERY TIER: `@SkipThrottle(SKIP_ALL_THROTTLERS)`.
//*
//* USE THIS AND NEVER THE BARE `@SkipThrottle()`. THE DECORATOR'S DEFAULT ARGUMENT IS
//* `{ default: true }` — IT SKIPS ONLY A THROTTLER LITERALLY NAMED "default", WHICH IS THE
//* NAME AN UNNAMED forRoot THROTTLER GETS. THE MOMENT THE TIERS BECAME NAMED short/long,
//* EVERY BARE @SkipThrottle() IN THE CODEBASE MATCHED NOTHING AND SILENTLY STOPPED
//* EXEMPTING ANYTHING. THAT IS NOT HYPOTHETICAL: IT WAS CAUGHT ON HealthController, WHERE
//* IT MEANT AN ORCHESTRATOR POLLING /health/live EVERY FEW SECONDS WOULD TRIP THE BURST
//* TIER AND GET THE POD KILLED FOR THE WRONG REASON — THE EXACT FAILURE THAT CONTROLLER'S
//* COMMENT WAS WRITTEN TO PREVENT. ADDING A NEW TIER MEANS ADDING IT HERE TOO.
export const SKIP_ALL_THROTTLERS: Record<string, boolean> = {
  [THROTTLER_SHORT]: true,
  [THROTTLER_LONG]: true,
};

//* ---------------------------------------------------------------------------
//* PER-ROUTE OVERRIDES FOR SECURITY-CRITICAL AND MAIL-SENDING ENDPOINTS.
//* VALUES COME STRAIGHT FROM docs/issues/rate-limiting.md §5.
//*
//* EACH IS APPLIED AS `@Throttle({ [THROTTLER_SHORT]: X })`, OVERRIDING ONLY THE `short`
//* TIER FOR THAT HANDLER. THE `long` TIER STAYS AT ITS GLOBAL SETTING AND CAN NEVER BIND
//* FIRST HERE, BECAUSE EVERY OVERRIDE BELOW IS STRICTLY TIGHTER THAN 200-PER-MINUTE —
//* YOU WOULD HAVE TO TRIP THE OVERRIDE LONG BEFORE THE SUSTAINED TIER NOTICED.
//*
//* WHY THESE ARE CODE CONSTANTS AND NOT THROTTLE_* ENV VARS, UNLIKE THE GLOBAL TIERS:
//* @Throttle() IS A DECORATOR, EVALUATED WHEN THE CONTROLLER FILE IS FIRST IMPORTED —
//* WHICH HAPPENS DURING MODULE RESOLUTION, BEFORE ConfigModule HAS LOADED ANY .env FILE
//* INTO process.env. AN ENV-DRIVEN VALUE HERE WOULD READ undefined AT DECORATION TIME AND
//* SILENTLY FALL BACK TO THE GLOBAL TIER — I.E. THE LIMIT WOULD LOOK CONFIGURED AND BE
//* 30-PER-10s INSTEAD OF 3-PER-HOUR. THE OPERATIONAL ESCAPE HATCH IS THROTTLE_ENABLED,
//* WHICH KILLS THE WHOLE LIMITER; RETUNING AN INDIVIDUAL ROUTE IS A CODE CHANGE ON PURPOSE.
//* THIS IS A DELIBERATE NARROWING OF THAT DOC'S §4.3, WHICH LISTED THROTTLE_AUTH_* VARS.
//* ---------------------------------------------------------------------------

//* SIGNUP SPAM AND MAIL-COST CONTROL. EVERY ACCEPTED CALL COSTS A REAL OUTBOUND EMAIL
//* (THE SIGNUP OTP), SO THE BUDGET IS DELIBERATELY TINY. NO blockDuration: A LEGITIMATE
//* USER WHO GENUINELY FAT-FINGERS THREE SIGNUPS SHOULD BE ABLE TO RETRY AFTER THE HOUR,
//* NOT SERVE AN EXTRA PENALTY ON TOP OF IT.
export const SIGNUP_THROTTLE = { limit: 3, ttl: 3_600_000 };

//* BCRYPT-EXPENSIVE AND SECURITY-CRITICAL. 5/MIN IS FAR ABOVE HUMAN BEHAVIOR. blockDuration
//* IS THE v6 FEATURE THAT MATTERS HERE — WITHOUT IT AN ATTACKER OVER THE LIMIT JUST WAITS
//* OUT ONE ttl AND RESUMES AT FULL RATE, SO THE SUSTAINED COST OF AN ATTACK IS ONLY ~50%
//* THROUGHPUT. WITH IT, TRIPPING THE LIMIT COSTS 15 MINUTES.
export const LOGIN_THROTTLE = { limit: 5, ttl: 60_000, blockDuration: 900_000 };

//* LEGITIMATE CLIENTS REFRESH RARELY; A BURST HERE INDICATES A TOKEN-REPLAY LOOP.
export const REFRESH_THROTTLE = { limit: 20, ttl: 60_000 };

//* OTP GUESSING. THIS IS THE PER-IP HALF ONLY — THE PER-OTP ATTEMPT CAP THAT STOPS A
//* DISTRIBUTED GUESSER IS PHASE 2 BUSINESS-LAYER WORK AND IS NOT IMPLEMENTED YET.
export const OTP_VERIFY_THROTTLE = {
  limit: 5,
  ttl: 300_000,
  blockDuration: 900_000,
};

//* OTP ISSUANCE — SAME OUTBOUND-MAIL COST AS SIGNUP. OtpService ALSO ENFORCES ITS OWN
//* RESEND_COOLDOWN_SECONDS PER IDENTITY; THIS IS THE PER-IP CEILING ON TOP OF THAT.
export const OTP_RESEND_THROTTLE = { limit: 3, ttl: 3_600_000 };
