import { z } from 'zod';

//* z.coerce.boolean() RUNS JS Boolean() ON THE RAW STRING — Boolean("false") IS true, SO
//* AN ENV VAR EXPLICITLY SET TO "false" WOULD COERCE TO true. SAME HELPER AS logger.env.ts.
const stringBoolean = () =>
  z.union([
    z.enum(['true', 'false']).transform((val) => val === 'true'),
    z.boolean(),
  ]);

//* SELF-CONTAINED ENV CONTRACT FOR THIS MODULE — NO DEPENDENCY ON THE APP SHELL'S config/env.validation.ts
//* LETS src/common/throttler BE COPIED INTO ANOTHER PROJECT AND VALIDATE ITSELF, WITH ZERO KNOWLEDGE OF UNRELATED DOMAINS
//*
//* EVERY WINDOW IS SUFFIXED _MS AND IS IN MILLISECONDS. THAT NAMING IS THE POINT:
//* @nestjs/throttler CHANGED ttl FROM SECONDS TO MILLISECONDS IN v5, AND THE CONFIG THIS
//* MODULE REPLACES (`ttl: 60` IN app.module.ts) WAS A 60-MILLISECOND WINDOW WEARING A
//* "RESET COUNTER AFTER 60 SECONDS" COMMENT. SEE docs/issues/rate-limiting.md §3.2.
export const throttlerEnvSchema = z.object({
  //* EMERGENCY KILL SWITCH. WIRED THROUGH skipIf, NOT THROUGH CONDITIONAL MODULE
  //* REGISTRATION — CONDITIONAL REGISTRATION CHANGES THE DI GRAPH BETWEEN ENVIRONMENTS,
  //* WHICH IS HOW "WORKS IN STAGING" BUGS ARE BORN. ALSO THE SWITCH e2e RUNS USE.
  THROTTLE_ENABLED: stringBoolean().default(true),

  //* BURST TIER — ABSORBS A PAGE LOAD'S PARALLEL XHRs, KILLS SCRIPTED FLOODS.
  THROTTLE_SHORT_TTL_MS: z.coerce.number().int().positive().default(10_000),
  THROTTLE_SHORT_LIMIT: z.coerce.number().int().positive().default(30),

  //* SUSTAINED TIER — THE REAL POLICY CEILING OVER A LONGER WINDOW.
  THROTTLE_LONG_TTL_MS: z.coerce.number().int().positive().default(60_000),
  THROTTLE_LONG_LIMIT: z.coerce.number().int().positive().default(200),

  //* HOW MANY REVERSE-PROXY HOPS TO TRUST WHEN DERIVING req.ip. 0 = TRUST NOTHING AND USE
  //* THE SOCKET IP, WHICH IS CORRECT FOR LOCAL/DIRECT-EXPOSURE RUNS. SET IT TO THE REAL HOP
  //* COUNT IN ANY ENVIRONMENT BEHIND A PROXY, OR EVERY CALLER SHARES THE PROXY'S IP AND
  //* THEREFORE ONE RATE-LIMIT BUCKET. CANNOT BE VALIDATED LOCALLY — SEE THE ROLLOUT NOTES
  //* IN docs/issues/rate-limiting.md §7.
  THROTTLE_TRUST_PROXY_HOPS: z.coerce.number().int().min(0).default(0),

  //* DECLARED BUT NOT YET CONSUMED — THIS APP RUNS SINGLE-INSTANCE AND USES THE BUILT-IN
  //* IN-MEMORY STORAGE. THE VAR EXISTS SO REDIS IS A CONFIG CHANGE PLUS ONE storage: LINE
  //* RATHER THAN A REFACTOR. AppThrottlerModule LOGS A LOUD WARNING IF IT IS SET, SO IT CAN
  //* NEVER SILENTLY LOOK LIKE DISTRIBUTED LIMITING IS ON WHEN IT ISN'T.
  THROTTLE_REDIS_URL: z.string().url().optional(),
});

export type ThrottlerEnv = z.infer<typeof throttlerEnvSchema>;
